### PR TITLE
Add image attachment to email

### PR DESCRIPTION
**Pull request by negbie**

### CODE REVIEW

**Comment by negasus** [comment]
It's not working for me (
Can you provide demo script for testing?

**Comment by negbie** [comment]
Could you tell me how it fails?

**Comment by negbie** [comment]
I used this lua script and it's working

```
-- @interval 5s

local alert = require('alert')
local chart = require('chart')
local chartOptions = {
    ['series'] = {
        {
            ['color'] = '#456789',
            ["data"] = {
                { ['timestamp'] = 12345646554, ['value'] = 95 },
                { ['timestamp'] = 12345646555, ['value'] = 94 },
                { ['timestamp'] = 12345646556, ['value'] = 97 },
                { ['timestamp'] = 12345646557, ['value'] = 93 }
            }
        },
        {
            ['color'] = 'red',
            ["data"] = {
                { ['timestamp'] = 12345646554, ['value'] = 85 },
                { ['timestamp'] = 12345646555, ['value'] = 84 },
                { ['timestamp'] = 12345646556, ['value'] = 87 },
                { ['timestamp'] = 12345646557, ['value'] = 83 }
            }
        }
    }
}

local img, err = chart.render('My Chart', chartOptions)
if err ~= nil then
    log.error('render error: ' .. err)
    return
end

alert.error('alert-id', 'An error occured!', { image = img })
```

**Comment by negbie** [comment]
alert-id

**Comment by negbie** [comment]
maildevattachment

**Comment by negasus** [comment]
I tested on real mail system (yandex.ru in my case), and i didn't saw an image. I will test with other mail systems later

**Comment by negbie** [comment]
I just tested with maildev and it worked. I would need more details how the message was delivered to yandex (mostly the smtp header)

**Comment by negbie** [comment]
@negasus I refactored email a bit and made email attachements work with upstream email providers. Instead of reinventing the wheel I used a small, well tested lib.

**Comment by negasus** [comment]
It's work!)

**Comment by negasus** [comment]
I think we should use the .png extension for attachment.

**Comment by negbie** [comment]
Ok done in latest commit. I've changed requireTLS to withoutTLS because TLS should alwas be on.
Now if you use any port beside 465 STARTTLS will be used. If you use 465 normal transport TLS will be used. If you don't want encryption you need to set in config.yml withoutTLS: true

**Comment by negasus** [comment]
I'm confused about use port = 456 and disableTLS option. Maybe use option 'secure' with values 'ssl', 'tls', 'none'?

**Comment by negbie** [comment]
I think this could confuse some people. For example most people will set it to TLS. Now if the configure port 465 it won't work. Other people will read SSL and think about heartblead.

Port 465 is always transport TLS.

**Comment by negbie** [comment]
I can rename it to disableTLS if you want. This makes it clear. No security at all.

**Comment by negasus** [comment]
I think, use 'secure' = 'tls', 'ssl', 'none' will be good
This will not bind to the value of the port.

**Comment by negbie** [comment]
Ok let me change that.

**Comment by negbie** [comment]
Ok done. It's a bit confusing to me not having port 465 using constant ssl. So now people need to know that they must set secure to ssl if the use port 465 otherwise it will not work on most email provider.

**Comment by negasus** [comment]
Ok! Add please one more thing: validation of the 'secure' option for 'ssl', 'tls' and 'none'

**Comment by negbie** [comment]
Done. Empty secure value "" is valid because I use tls as default.

**Comment by negbie** [comment]
Btw I would still prefer to add this condition for user a better user experience:

```
	if server.Port == 465 {
		server.Encryption = mail.EncryptionSSL
	}
```

**Comment by negasus** [comment]
we can add forced secure = 'ssl' for port value '465' if the 'secure' option is empty. and we should print Info message about it on start Balerter

**Comment by negbie** [comment]
Good idea!

**Comment by negbie** [comment]
I will add it after lunch ;)

**Comment by negbie** [comment]
Please take a look if the logging is ok for you.

**Comment by negasus** [comment]
Great!)

**Comment by negasus** [comment]
Can you resolve conflicts for merge?

**Pull request merged**
