### PR TITLE
Add lua csv module

### PR DESCRIPTION
**Pull request by negbie**

### CODE REVIEW

**Comment by negbie** [comment]
@negasus please take a look if it's ok for you.

**Comment by negbie** [comment]
Currently I kept the function names like the lib provided them but if you want we can rename

csv.parse()
csv.parseLine()

to

csv.decode()
csv.decodeLine()

**Comment by negbie** [comment]
If you want parse a string you can use

csv.parse("a,b,c\r\n1,2,3", ",", {loadFromString=true})

**Comment by negasus** [comment]
It looks great. I checked it works

**Comment by negasus** [comment]
It would be great to add documentation)

**Comment by negbie** [comment]
Yeah, but I'm not sure whats the best way to do it? Currently you use only the homepage right?

**Comment by negasus** [comment]
Currently the documentation placed in https://github.com/balerter/site

**Pull request merged**
